
development:
  adapter: postgresql
  encoding: unicode
  database: cool_io_development
  pool: 5
  username: DtotheFP
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cool_io_test
  pool: 5
  username: DtotheFP
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cool_io_production
  pool: 5
  username: DtotheFP
  password:
